"""
Canonical Parameter Registry and Critical Identification Audit
Governing Standard: BCRG Behavioral Parameter Audit (BPA) & Token Engineering Canon
"""
from typing import Dict, Any, List
import pandas as pd

PARAMETER_REGISTRY: List[Dict[str, Any]] = [
    # --------------------------------------------------------------------------
    # 1. CORE TRANCHING & BALANCE SHEET PARAMETERS
    # --------------------------------------------------------------------------
    {
        "id": "R",
        "symbol": "R",
        "name": "Senior Class A Coupon Rate",
        "subsystem": "Tranching",
        "unit": "annualized fraction (p.a.)",
        "baseline_value": 0.0730,
        "whitepaper_range": [0.040, 0.120],
        "hard_bounds": [0.010, 0.250],
        "plausible_range": [0.055, 0.085],
        "stress_range": [0.010, 0.200],
        "classification": "Governance / Design Parameter",
        "justification_source": "Circular In-Sample Simulation & Heuristic Alignment",
        "audit_commentary": "Set to 7.30% to exceed baseline staking yield q (6.0%) plus a 130 bps premium. However, the exact 7.30% value was tuned to produce low peg volatility in the same cadCAD runs reported in the paper. Highly collinear with R' and q; not uniquely identifiable from solvency constraints alone.",
        "identifiable_from_data": False,
        "is_arbitrary": True
    },
    {
        "id": "R_prime",
        "symbol": "R'",
        "name": "anUSD Benchmark Coupon Rate",
        "subsystem": "Tranching",
        "unit": "annualized fraction (p.a.)",
        "baseline_value": 0.0300,
        "whitepaper_range": [0.010, 0.050],
        "hard_bounds": [0.000, 0.100],
        "plausible_range": [0.015, 0.045],
        "stress_range": [0.000, 0.080],
        "classification": "Governance / Design Parameter",
        "justification_source": "Inherited Market Heuristic (Money Market Parity)",
        "audit_commentary": "Derived from traditional USD money-market benchmark rates (SOFR/Treasuries minus management fee). Provides positive carry for holding anUSD. Analytically constrained by (R' - 2R)T - 1 <= 0 for Theorem 1.",
        "identifiable_from_data": False,
        "is_arbitrary": False
    },
    {
        "id": "R_tilde",
        "symbol": "\\tilde{R}",
        "name": "Bear-Market Coupon Subsidy Rate",
        "subsystem": "Tranching",
        "unit": "annualized fraction (p.a.)",
        "baseline_value": 0.1000,
        "whitepaper_range": [0.050, 0.200],
        "hard_bounds": [0.000, 0.300],
        "plausible_range": [0.050, 0.150],
        "stress_range": [0.000, 0.250],
        "classification": "Governance / Mechanism Parameter",
        "justification_source": "Inherited from SSRN-3856569 (Cao et al., 2021)",
        "audit_commentary": "Directly inherited from Cao et al. (2021) Section 2.4. Intended to subsidize Class B equity during downward resets. Has weak empirical grounding for crypto-native user risk preferences; acts as an arbitrary wealth transfer.",
        "identifiable_from_data": False,
        "is_arbitrary": True
    },
    {
        "id": "alpha",
        "symbol": "\\alpha",
        "name": "Primary Tranche Split Ratio",
        "subsystem": "Tranching",
        "unit": "dimensionless ratio",
        "baseline_value": 1.0000,
        "whitepaper_range": [0.50, 2.00],
        "hard_bounds": [0.20, 5.00],
        "plausible_range": [0.80, 1.20],
        "stress_range": [0.50, 2.00],
        "classification": "Mathematically Determined / Structural Parameter",
        "justification_source": "Analytical Symmetry Requirement (SSRN-3856569)",
        "audit_commentary": "Set to 1.0 for 1:1 pair symmetry (1 unit of Class A matched with 1 unit of Class B). Structurally sound; deviations from 1.0 alter baseline leverage away from 2.0x.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "T",
        "symbol": "T",
        "name": "Contract Epoch Horizon / Maturity",
        "subsystem": "Tranching",
        "unit": "years (days)",
        "baseline_value": 1.0000,
        "whitepaper_range": [0.25, 2.00],
        "hard_bounds": [0.08, 5.00],
        "plausible_range": [0.50, 1.50],
        "stress_range": [0.25, 3.00],
        "classification": "Governance / Operational Parameter",
        "justification_source": "Standard Annual Accounting Convention",
        "audit_commentary": "Standard 365-day rollover convention. Dynamic resets occur much earlier on average (tau ~ 0.87 years), making T largely inactive except in prolonged sideways market regimes.",
        "identifiable_from_data": False,
        "is_arbitrary": False
    },

    # --------------------------------------------------------------------------
    # 2. DYNAMIC RESET STATE MACHINE PARAMETERS
    # --------------------------------------------------------------------------
    {
        "id": "H_u",
        "symbol": "H_u",
        "name": "Upward Dynamic Reset Barrier",
        "subsystem": "Dynamic Resets",
        "unit": "USD Net Asset Value ($)",
        "baseline_value": 2.0000,
        "whitepaper_range": [1.50, 3.00],
        "hard_bounds": [1.10, 5.00],
        "plausible_range": [1.75, 2.50],
        "stress_range": [1.30, 4.00],
        "classification": "Governance / Mechanism Parameter",
        "justification_source": "Analytical 100% Profit Realization Target (SSRN-3856569)",
        "audit_commentary": "Corresponds to 100% gain on Class B equity (NAV doubling from $1.00 to $2.00). Restores leverage from 1.5x back to 2.0x. Higher H_u reduces reset frequency but allows leverage to decay towards 1.0x.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "H_d",
        "symbol": "H_d",
        "name": "Downward Dynamic Reset Barrier",
        "subsystem": "Dynamic Resets",
        "unit": "USD Net Asset Value ($)",
        "baseline_value": 0.2500,
        "whitepaper_range": [0.15, 0.40],
        "hard_bounds": [0.05, 0.80],
        "plausible_range": [0.20, 0.35],
        "stress_range": [0.10, 0.50],
        "classification": "Security / Mechanism Threshold",
        "justification_source": "Theorem 1 Analytical Single-Step Crash Invariance Proof",
        "audit_commentary": "Mathematically critical: H_d directly determines the single-step crash tolerance Delta P_max = 0.5/(1 + H_d) - 1 = -60.0%. Lower H_d increases crash tolerance but increases maximum leverage at the barrier (Lambda_B = 2*S/0.25 = 5.0x). High identification priority.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "mu_split",
        "symbol": "\\mu_{\\text{split}}",
        "name": "Upward Forward Split Multiplier",
        "subsystem": "Dynamic Resets",
        "unit": "dimensionless scalar multiplier",
        "baseline_value": 1.5000,
        "whitepaper_range": [1.20, 2.00],
        "hard_bounds": [1.05, 3.00],
        "plausible_range": [1.30, 1.80],
        "stress_range": [1.10, 2.50],
        "classification": "Mathematically Determined / Rebase Parameter",
        "justification_source": "SSRN-3856569 Balance Sheet Restructuring Formula",
        "audit_commentary": "Determined by realized equity profit distribution ((V_B - 1.0) / 1.0). Scales share balance while reducing NAV back to $1.00.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "mu_merge",
        "symbol": "\\mu_{\\text{merge}}",
        "name": "Downward Reverse Split Multiplier",
        "subsystem": "Dynamic Resets",
        "unit": "dimensionless scalar multiplier",
        "baseline_value": 0.7500,
        "whitepaper_range": [0.50, 0.90],
        "hard_bounds": [0.10, 0.95],
        "plausible_range": [0.60, 0.85],
        "stress_range": [0.25, 0.90],
        "classification": "Mathematically Determined / Rebase Parameter",
        "justification_source": "SSRN-3856569 Senior Principal Amortization Formula",
        "audit_commentary": "Determined by equity factor V_B at trigger time. Exactly preserves solvency by returning unbacked Class A principal.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },

    # --------------------------------------------------------------------------
    # 3. CONTROL SYSTEM (REFLEXER DYNAMIC RATE) PARAMETERS
    # --------------------------------------------------------------------------
    {
        "id": "K_p",
        "symbol": "K_p",
        "name": "Proportional Controller Gain",
        "subsystem": "Control System",
        "unit": "1 / (USD * year)",
        "baseline_value": 0.1500,
        "whitepaper_range": [0.010, 1.000],
        "hard_bounds": [0.001, 5.000],
        "plausible_range": [0.050, 0.300],
        "stress_range": [0.000, 2.000],
        "classification": "Controller Tuning Parameter",
        "justification_source": "Root-Locus Overdamping Requirement (zeta >= 1.0)",
        "audit_commentary": "Tuned to achieve overdamped response (zeta = 17.03) under assumed AMM liquidity depth ($20M). Under low liquidity ($2M), high K_p causes aggressive rate overshoot and secondary peg oscillations. Needs robust bounds across liquidity regimes.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "K_i",
        "symbol": "K_i",
        "name": "Integral Controller Gain",
        "subsystem": "Control System",
        "unit": "1 / (USD * year^2)",
        "baseline_value": 0.0200,
        "whitepaper_range": [0.001, 0.100],
        "hard_bounds": [0.000, 1.000],
        "plausible_range": [0.005, 0.050],
        "stress_range": [0.000, 0.200],
        "classification": "Controller Tuning Parameter",
        "justification_source": "Steady-State Error Elimination Heuristic",
        "audit_commentary": "Eliminates steady-state peg offset on secondary AMMs. Susceptible to integral windup during prolonged liquidity shocks unless strictly clamped.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "K_d",
        "symbol": "K_d",
        "name": "Derivative Controller Gain",
        "subsystem": "Control System",
        "unit": "dimensionless (USD / USD)",
        "baseline_value": 0.0050,
        "whitepaper_range": [0.000, 0.050],
        "hard_bounds": [0.000, 0.200],
        "plausible_range": [0.000, 0.015],
        "stress_range": [0.000, 0.100],
        "classification": "Controller Tuning Parameter",
        "justification_source": "High-Frequency Oscillation Damping Heuristic",
        "audit_commentary": "D-term noise amplification is a major practical risk on discrete on-chain DEX price feeds. Setting K_d = 0 (PI controller) produces virtually identical damping without noise sensitivity. K_d is largely redundant.",
        "identifiable_from_data": False,
        "is_arbitrary": True
    },
    {
        "id": "max_rate_clamp",
        "symbol": "\\Delta R'_{\\max}",
        "name": "Maximum Dynamic Rate Modulation Clamp",
        "subsystem": "Control System",
        "unit": "annualized fraction (p.a.)",
        "baseline_value": 0.0500,
        "whitepaper_range": [0.020, 0.100],
        "hard_bounds": [0.010, 0.250],
        "plausible_range": [0.030, 0.080],
        "stress_range": [0.010, 0.150],
        "classification": "Security / Anti-Windup Guard",
        "justification_source": "Anti-Windup Rate Safety Heuristic",
        "audit_commentary": "Prevents interest rate from exploding to unrealistic levels (+/- 5.0% p.a.). Pragmatic guard preventing runaway protocol yield obligations during black swans.",
        "identifiable_from_data": False,
        "is_arbitrary": False
    },
    {
        "id": "twap_window",
        "symbol": "\\Delta t_{\\text{sample}}",
        "name": "DEX TWAP Sampling Duration",
        "subsystem": "Control System",
        "unit": "seconds (minutes)",
        "baseline_value": 1800.0,
        "whitepaper_range": [600.0, 7200.0],
        "hard_bounds": [60.0, 86400.0],
        "plausible_range": [900.0, 3600.0],
        "stress_range": [300.0, 7200.0],
        "classification": "Oracle / Security Parameter",
        "justification_source": "Standard DeFi 30-Minute TWAP Convention (Uniswap V3)",
        "audit_commentary": "Filters out flash-loan price manipulation while introducing a 15-minute phase lag in controller actuation. Good trade-off between manipulation cost and responsiveness.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },

    # --------------------------------------------------------------------------
    # 4. ACP-67 TOKENOMICS & DYNAMIC VALIDATOR SUBSIDY PARAMETERS
    # --------------------------------------------------------------------------
    {
        "id": "omega_burn",
        "symbol": "\\omega_{\\text{burn}}",
        "name": "AVAX Buyback & Burn Allocation Share",
        "subsystem": "Tokenomics",
        "unit": "fraction of gross yield",
        "baseline_value": 0.6500,
        "whitepaper_range": [0.400, 0.800],
        "hard_bounds": [0.100, 0.900],
        "plausible_range": [0.500, 0.750],
        "stress_range": [0.200, 0.850],
        "classification": "Governance / Policy Parameter",
        "justification_source": "Avalanche Community Proposal ACP-67 (Discussion #293)",
        "audit_commentary": "Directly mandated by ACP-67 community proposal for AVAX supply deflation. Not derived from a mathematical optimum; purely a governance preference balancing deflation vs validator support.",
        "identifiable_from_data": False,
        "is_arbitrary": False
    },
    {
        "id": "omega_val",
        "symbol": "\\omega_{\\text{val}}",
        "name": "Baseline Validator Incentive Boost Share",
        "subsystem": "Tokenomics",
        "unit": "fraction of gross yield",
        "baseline_value": 0.2000,
        "whitepaper_range": [0.100, 0.350],
        "hard_bounds": [0.050, 0.600],
        "plausible_range": [0.150, 0.300],
        "stress_range": [0.050, 0.500],
        "classification": "Governance / Policy Parameter",
        "justification_source": "ACP-67 Governance Consensus",
        "audit_commentary": "Baseline validator revenue share during normal market regimes. Dynamically expands up to 45% during market drawdowns.",
        "identifiable_from_data": False,
        "is_arbitrary": False
    },
    {
        "id": "omega_l1",
        "symbol": "\\omega_{\\text{l1}}",
        "name": "Sovereign L1 & Ecosystem Grants Share",
        "subsystem": "Tokenomics",
        "unit": "fraction of gross yield",
        "baseline_value": 0.1500,
        "whitepaper_range": [0.050, 0.250],
        "hard_bounds": [0.000, 0.400],
        "plausible_range": [0.100, 0.200],
        "stress_range": [0.000, 0.300],
        "classification": "Governance / Policy Parameter",
        "justification_source": "ACP-67 Ecosystem Teleporter Bootstrapping",
        "audit_commentary": "Residual share to bootstrap cross-L1 Teleporter liquidity routes. Governance choice.",
        "identifiable_from_data": False,
        "is_arbitrary": False
    },
    {
        "id": "kappa_drawdown",
        "symbol": "\\kappa_{\\text{drawdown}}",
        "name": "Validator Subsidy Drawdown Responsiveness",
        "subsystem": "Tokenomics",
        "unit": "dimensionless sensitivity coefficient",
        "baseline_value": 0.3500,
        "whitepaper_range": [0.150, 0.600],
        "hard_bounds": [0.000, 1.000],
        "plausible_range": [0.250, 0.450],
        "stress_range": [0.100, 0.800],
        "classification": "Behavioral / Policy Sensitivity Coefficient",
        "justification_source": "BCRG Validator OpEx Insolvency Modeling",
        "audit_commentary": "Scales validator share proportionally to EMA price drawdowns to prevent independent node operator OpEx insolvencies ($350/mo). Calibrated against 1,450 active Avalanche validator node OpEx distributions.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },

    # --------------------------------------------------------------------------
    # 5. MARKET, ORACLE & SECURITY PARAMETERS
    # --------------------------------------------------------------------------
    {
        "id": "delta_lock",
        "symbol": "\\delta_{\\text{lock}}",
        "name": "MEV Proximity State-Lock Band",
        "subsystem": "Security / Oracles",
        "unit": "percentage band around barrier (+/- %)",
        "baseline_value": 0.0150,
        "whitepaper_range": [0.005, 0.030],
        "hard_bounds": [0.002, 0.080],
        "plausible_range": [0.010, 0.025],
        "stress_range": [0.005, 0.050],
        "classification": "Security Threshold",
        "justification_source": "MEV Maximum Profitable Manipulation Cost (MPMC) Model",
        "audit_commentary": "Enforces 1-block commit-delay lock when oracle is within +/- 1.5% of H_u or H_d. Raises attack cost to > $45M, eliminating flash-loan sandwich arbitrage.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "delta_p_max",
        "symbol": "\\Delta P_{\\max}",
        "name": "Oracle Spot vs TWAP Circuit Breaker Divergence",
        "subsystem": "Security / Oracles",
        "unit": "percentage divergence (+/- %)",
        "baseline_value": 0.0800,
        "whitepaper_range": [0.030, 0.150],
        "hard_bounds": [0.010, 0.300],
        "plausible_range": [0.050, 0.100],
        "stress_range": [0.020, 0.200],
        "classification": "Security Threshold",
        "justification_source": "Flash-Loan Oracle Manipulation Bounds",
        "audit_commentary": "Pauses primary mint/redeem if spot oracle diverges > 8.0% from 30-min TWAP. Prevents single-block oracle manipulation while avoiding false-positive halts during genuine high-volatility flash crashes.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "tau_heart",
        "symbol": "\\tau_{\\text{heart}}",
        "name": "Max Oracle Staleness Heartbeat",
        "subsystem": "Security / Oracles",
        "unit": "seconds",
        "baseline_value": 300.0,
        "whitepaper_range": [60.0, 900.0],
        "hard_bounds": [10.0, 86400.0],
        "plausible_range": [120.0, 600.0],
        "stress_range": [60.0, 3600.0],
        "classification": "Security Threshold",
        "justification_source": "Chainlink AVAX/USD Mainnet Feed Specification",
        "audit_commentary": "Matches Chainlink AVAX/USD standard heartbeat of 300 seconds (or 0.5% deviation). Sound empirical grounding.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "f_mint",
        "symbol": "f_{\\text{mint}}",
        "name": "Primary Vault Issuance Fee",
        "subsystem": "Market Microstructure",
        "unit": "basis points (fraction)",
        "baseline_value": 0.0010,
        "whitepaper_range": [0.000, 0.005],
        "hard_bounds": [0.000, 0.020],
        "plausible_range": [0.0005, 0.0025],
        "stress_range": [0.000, 0.010],
        "classification": "Market / Fee Parameter",
        "justification_source": "DeFi Standard Primary Issuance Fee (10 bps)",
        "audit_commentary": "Standard 10 bps issuance fee. Prevents spam mints and routes fees into ACP-67 waterfall.",
        "identifiable_from_data": False,
        "is_arbitrary": False
    },

    # --------------------------------------------------------------------------
    # 6. STOCHASTIC COLLATERAL & MACRO MODEL PARAMETERS
    # --------------------------------------------------------------------------
    {
        "id": "sigma",
        "symbol": "\\sigma",
        "name": "Continuous Annualized AVAX Volatility",
        "subsystem": "Stochastic Environment",
        "unit": "annualized standard deviation",
        "baseline_value": 0.8986,
        "whitepaper_range": [0.500, 1.200],
        "hard_bounds": [0.200, 2.500],
        "plausible_range": [0.650, 1.100],
        "stress_range": [0.400, 1.800],
        "classification": "Empirically Estimated Parameter",
        "justification_source": "5-Year AVAX/USD Historical Telemetry (2021-2026)",
        "audit_commentary": "Empirically calibrated from 1,826 daily log-returns of AVAX/USD. 89.86% is a genuine historical estimate. However, treating it as a fixed constant is dangerous; volatility clusters between 45% (calm) and 160% (crash regimes).",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "lambda_jump",
        "symbol": "\\lambda",
        "name": "Poisson Jump Intensity",
        "subsystem": "Stochastic Environment",
        "unit": "jumps / year",
        "baseline_value": 2.4000,
        "whitepaper_range": [1.000, 6.000],
        "hard_bounds": [0.100, 20.000],
        "plausible_range": [1.500, 4.000],
        "stress_range": [0.500, 12.000],
        "classification": "Empirically Estimated Parameter",
        "justification_source": "Kou Jump-Diffusion Maximum Likelihood Estimation",
        "audit_commentary": "Estimated via MLE on 3-sigma tail events of AVAX returns. 2.4 jumps/year is well supported. Subject to regime shifts during systemic crypto crises.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "p_jump",
        "symbol": "p",
        "name": "Upward Jump Probability",
        "subsystem": "Stochastic Environment",
        "unit": "probability (fraction)",
        "baseline_value": 0.4000,
        "whitepaper_range": [0.200, 0.600],
        "hard_bounds": [0.050, 0.950],
        "plausible_range": [0.300, 0.500],
        "stress_range": [0.100, 0.700],
        "classification": "Empirically Estimated Parameter",
        "justification_source": "Asymmetric Jump Tail Ratio (Kou, 2002)",
        "audit_commentary": "Reflects negative tail asymmetry in crypto (60% downward jumps, 40% upward jumps). Well grounded empirically.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "eta_1",
        "symbol": "\\eta_1",
        "name": "Upward Jump Decay Parameter",
        "subsystem": "Stochastic Environment",
        "unit": "rate parameter (1 / jump magnitude)",
        "baseline_value": 3.5000,
        "whitepaper_range": [2.000, 6.000],
        "hard_bounds": [1.100, 15.000],
        "plausible_range": [2.500, 4.500],
        "stress_range": [1.500, 8.000],
        "classification": "Empirically Estimated Parameter",
        "justification_source": "Exponential Tail MLE (Mean Upward Jump = +28.6%)",
        "audit_commentary": "Governs the magnitude of upward jumps (E[Y|Y>0] = 1/eta_1 = +28.57%). Statistically identified from tail distribution.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "eta_2",
        "symbol": "\\eta_2",
        "name": "Downward Jump Decay Parameter",
        "subsystem": "Stochastic Environment",
        "unit": "rate parameter (1 / jump magnitude)",
        "baseline_value": 2.0000,
        "whitepaper_range": [1.200, 4.000],
        "hard_bounds": [0.500, 10.000],
        "plausible_range": [1.500, 2.800],
        "stress_range": [0.800, 5.000],
        "classification": "Empirically Estimated Parameter",
        "justification_source": "Exponential Tail MLE (Mean Downward Jump = -50.0%)",
        "audit_commentary": "Governs the magnitude of downward crashes (E[Y|Y<0] = 1/eta_2 = -50.0%). Crucial driver of black swan stress. Highly identified from tail crashes.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "q",
        "symbol": "q",
        "name": "Continuous Liquid Staking Yield",
        "subsystem": "Stochastic Environment",
        "unit": "annualized fraction (p.a.)",
        "baseline_value": 0.0600,
        "whitepaper_range": [0.040, 0.080],
        "hard_bounds": [0.010, 0.150],
        "plausible_range": [0.050, 0.075],
        "stress_range": [0.020, 0.120],
        "classification": "Empirically Estimated / On-Chain Variable",
        "justification_source": "Avalanche Primary Network Staking Rewards (Benqi / GoGoPool)",
        "audit_commentary": "Directly observed from on-chain staking contracts. Compresses over time as total staked AVAX rises and issuance reward rates decay post ACP-77/ACP-285.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    },
    {
        "id": "r_rf",
        "symbol": "r",
        "name": "Continuous Risk-Free Discount Rate",
        "subsystem": "Stochastic Environment",
        "unit": "annualized fraction (p.a.)",
        "baseline_value": 0.0350,
        "whitepaper_range": [0.010, 0.060],
        "hard_bounds": [0.000, 0.150],
        "plausible_range": [0.020, 0.050],
        "stress_range": [0.000, 0.100],
        "classification": "Macroeconomic Exogenous Benchmark",
        "justification_source": "US Federal Reserve Short-Term Treasury Yield (SOFR)",
        "audit_commentary": "Exogenous macro rate used for risk-neutral PIDE discounting. Well grounded in US financial markets.",
        "identifiable_from_data": True,
        "is_arbitrary": False
    }
]

def get_parameter_dataframe() -> pd.DataFrame:
    return pd.DataFrame(PARAMETER_REGISTRY)

if __name__ == "__main__":
    df = get_parameter_dataframe()
    print(f"Total Parameters Audited: {len(df)}")
    print(df[["id", "symbol", "baseline_value", "classification", "is_arbitrary"]])
